-- =========================================================================
-- Top of Non League — seed the real 2026/27 Isthmian Premier Division
-- fixture list (22 teams, 42 game weeks, 462 fixtures).
--
-- Paste this whole file into the Supabase SQL Editor and click Run. Safe to
-- run more than once — teams and game weeks use ON CONFLICT DO NOTHING, and
-- the fixtures insert is guarded by a check so it won't duplicate rows if
-- fixtures already exist for this league/season.
-- =========================================================================

insert into public.teams (league_slug, name) values
  ('isthmian-premier', 'AFC Whyteleafe'),
  ('isthmian-premier', 'Aveley'),
  ('isthmian-premier', 'Brentwood Town'),
  ('isthmian-premier', 'Burgess Hill Town'),
  ('isthmian-premier', 'Carshalton Athletic'),
  ('isthmian-premier', 'Chatham Town'),
  ('isthmian-premier', 'Cheshunt'),
  ('isthmian-premier', 'Cray Wanderers'),
  ('isthmian-premier', 'Dartford'),
  ('isthmian-premier', 'Dulwich Hamlet'),
  ('isthmian-premier', 'Eastbourne Borough'),
  ('isthmian-premier', 'Enfield Town'),
  ('isthmian-premier', 'Leatherhead'),
  ('isthmian-premier', 'Lewes'),
  ('isthmian-premier', 'Maldon & Tiptree'),
  ('isthmian-premier', 'Ramsgate'),
  ('isthmian-premier', 'St Albans City'),
  ('isthmian-premier', 'Stanway Rovers'),
  ('isthmian-premier', 'Three Bridges'),
  ('isthmian-premier', 'Welling United'),
  ('isthmian-premier', 'Whitehawk'),
  ('isthmian-premier', 'Wingate & Finchley')
on conflict (league_slug, name) do nothing;

insert into public.gameweeks (league_slug, season, number) values
  ('isthmian-premier', '2026-27', 1),
  ('isthmian-premier', '2026-27', 2),
  ('isthmian-premier', '2026-27', 3),
  ('isthmian-premier', '2026-27', 4),
  ('isthmian-premier', '2026-27', 5),
  ('isthmian-premier', '2026-27', 6),
  ('isthmian-premier', '2026-27', 7),
  ('isthmian-premier', '2026-27', 8),
  ('isthmian-premier', '2026-27', 9),
  ('isthmian-premier', '2026-27', 10),
  ('isthmian-premier', '2026-27', 11),
  ('isthmian-premier', '2026-27', 12),
  ('isthmian-premier', '2026-27', 13),
  ('isthmian-premier', '2026-27', 14),
  ('isthmian-premier', '2026-27', 15),
  ('isthmian-premier', '2026-27', 16),
  ('isthmian-premier', '2026-27', 17),
  ('isthmian-premier', '2026-27', 18),
  ('isthmian-premier', '2026-27', 19),
  ('isthmian-premier', '2026-27', 20),
  ('isthmian-premier', '2026-27', 21),
  ('isthmian-premier', '2026-27', 22),
  ('isthmian-premier', '2026-27', 23),
  ('isthmian-premier', '2026-27', 24),
  ('isthmian-premier', '2026-27', 25),
  ('isthmian-premier', '2026-27', 26),
  ('isthmian-premier', '2026-27', 27),
  ('isthmian-premier', '2026-27', 28),
  ('isthmian-premier', '2026-27', 29),
  ('isthmian-premier', '2026-27', 30),
  ('isthmian-premier', '2026-27', 31),
  ('isthmian-premier', '2026-27', 32),
  ('isthmian-premier', '2026-27', 33),
  ('isthmian-premier', '2026-27', 34),
  ('isthmian-premier', '2026-27', 35),
  ('isthmian-premier', '2026-27', 36),
  ('isthmian-premier', '2026-27', 37),
  ('isthmian-premier', '2026-27', 38),
  ('isthmian-premier', '2026-27', 39),
  ('isthmian-premier', '2026-27', 40),
  ('isthmian-premier', '2026-27', 41),
  ('isthmian-premier', '2026-27', 42)
on conflict (league_slug, season, number) do nothing;

insert into public.fixtures (gameweek_id, home_team_id, away_team_id)
select gw.id, home.id, away.id
from (values
  (1, 'AFC Whyteleafe', 'Wingate & Finchley'),
  (1, 'Aveley', 'Whitehawk'),
  (1, 'Brentwood Town', 'Welling United'),
  (1, 'Burgess Hill Town', 'Three Bridges'),
  (1, 'Carshalton Athletic', 'Stanway Rovers'),
  (1, 'Chatham Town', 'St Albans City'),
  (1, 'Cheshunt', 'Ramsgate'),
  (1, 'Cray Wanderers', 'Maldon & Tiptree'),
  (1, 'Dartford', 'Lewes'),
  (1, 'Dulwich Hamlet', 'Leatherhead'),
  (1, 'Eastbourne Borough', 'Enfield Town'),
  (2, 'Whitehawk', 'AFC Whyteleafe'),
  (2, 'Wingate & Finchley', 'Welling United'),
  (2, 'Aveley', 'Three Bridges'),
  (2, 'Brentwood Town', 'Stanway Rovers'),
  (2, 'Burgess Hill Town', 'St Albans City'),
  (2, 'Carshalton Athletic', 'Ramsgate'),
  (2, 'Chatham Town', 'Maldon & Tiptree'),
  (2, 'Cheshunt', 'Lewes'),
  (2, 'Cray Wanderers', 'Leatherhead'),
  (2, 'Dartford', 'Enfield Town'),
  (2, 'Dulwich Hamlet', 'Eastbourne Borough'),
  (3, 'AFC Whyteleafe', 'Welling United'),
  (3, 'Whitehawk', 'Three Bridges'),
  (3, 'Wingate & Finchley', 'Stanway Rovers'),
  (3, 'Aveley', 'St Albans City'),
  (3, 'Brentwood Town', 'Ramsgate'),
  (3, 'Burgess Hill Town', 'Maldon & Tiptree'),
  (3, 'Carshalton Athletic', 'Lewes'),
  (3, 'Chatham Town', 'Leatherhead'),
  (3, 'Cheshunt', 'Enfield Town'),
  (3, 'Cray Wanderers', 'Eastbourne Borough'),
  (3, 'Dartford', 'Dulwich Hamlet'),
  (4, 'Three Bridges', 'AFC Whyteleafe'),
  (4, 'Welling United', 'Stanway Rovers'),
  (4, 'Whitehawk', 'St Albans City'),
  (4, 'Wingate & Finchley', 'Ramsgate'),
  (4, 'Aveley', 'Maldon & Tiptree'),
  (4, 'Brentwood Town', 'Lewes'),
  (4, 'Burgess Hill Town', 'Leatherhead'),
  (4, 'Carshalton Athletic', 'Enfield Town'),
  (4, 'Chatham Town', 'Eastbourne Borough'),
  (4, 'Cheshunt', 'Dulwich Hamlet'),
  (4, 'Cray Wanderers', 'Dartford'),
  (5, 'AFC Whyteleafe', 'Stanway Rovers'),
  (5, 'Three Bridges', 'St Albans City'),
  (5, 'Welling United', 'Ramsgate'),
  (5, 'Whitehawk', 'Maldon & Tiptree'),
  (5, 'Wingate & Finchley', 'Lewes'),
  (5, 'Aveley', 'Leatherhead'),
  (5, 'Brentwood Town', 'Enfield Town'),
  (5, 'Burgess Hill Town', 'Eastbourne Borough'),
  (5, 'Carshalton Athletic', 'Dulwich Hamlet'),
  (5, 'Chatham Town', 'Dartford'),
  (5, 'Cheshunt', 'Cray Wanderers'),
  (6, 'St Albans City', 'AFC Whyteleafe'),
  (6, 'Stanway Rovers', 'Ramsgate'),
  (6, 'Three Bridges', 'Maldon & Tiptree'),
  (6, 'Welling United', 'Lewes'),
  (6, 'Whitehawk', 'Leatherhead'),
  (6, 'Wingate & Finchley', 'Enfield Town'),
  (6, 'Aveley', 'Eastbourne Borough'),
  (6, 'Brentwood Town', 'Dulwich Hamlet'),
  (6, 'Burgess Hill Town', 'Dartford'),
  (6, 'Carshalton Athletic', 'Cray Wanderers'),
  (6, 'Chatham Town', 'Cheshunt'),
  (7, 'AFC Whyteleafe', 'Ramsgate'),
  (7, 'St Albans City', 'Maldon & Tiptree'),
  (7, 'Stanway Rovers', 'Lewes'),
  (7, 'Three Bridges', 'Leatherhead'),
  (7, 'Welling United', 'Enfield Town'),
  (7, 'Whitehawk', 'Eastbourne Borough'),
  (7, 'Wingate & Finchley', 'Dulwich Hamlet'),
  (7, 'Aveley', 'Dartford'),
  (7, 'Brentwood Town', 'Cray Wanderers'),
  (7, 'Burgess Hill Town', 'Cheshunt'),
  (7, 'Carshalton Athletic', 'Chatham Town'),
  (8, 'Maldon & Tiptree', 'AFC Whyteleafe'),
  (8, 'Ramsgate', 'Lewes'),
  (8, 'St Albans City', 'Leatherhead'),
  (8, 'Stanway Rovers', 'Enfield Town'),
  (8, 'Three Bridges', 'Eastbourne Borough'),
  (8, 'Welling United', 'Dulwich Hamlet'),
  (8, 'Whitehawk', 'Dartford'),
  (8, 'Wingate & Finchley', 'Cray Wanderers'),
  (8, 'Aveley', 'Cheshunt'),
  (8, 'Brentwood Town', 'Chatham Town'),
  (8, 'Burgess Hill Town', 'Carshalton Athletic'),
  (9, 'AFC Whyteleafe', 'Lewes'),
  (9, 'Maldon & Tiptree', 'Leatherhead'),
  (9, 'Ramsgate', 'Enfield Town'),
  (9, 'St Albans City', 'Eastbourne Borough'),
  (9, 'Stanway Rovers', 'Dulwich Hamlet'),
  (9, 'Three Bridges', 'Dartford'),
  (9, 'Welling United', 'Cray Wanderers'),
  (9, 'Whitehawk', 'Cheshunt'),
  (9, 'Wingate & Finchley', 'Chatham Town'),
  (9, 'Aveley', 'Carshalton Athletic'),
  (9, 'Brentwood Town', 'Burgess Hill Town'),
  (10, 'Leatherhead', 'AFC Whyteleafe'),
  (10, 'Lewes', 'Enfield Town'),
  (10, 'Maldon & Tiptree', 'Eastbourne Borough'),
  (10, 'Ramsgate', 'Dulwich Hamlet'),
  (10, 'St Albans City', 'Dartford'),
  (10, 'Stanway Rovers', 'Cray Wanderers'),
  (10, 'Three Bridges', 'Cheshunt'),
  (10, 'Welling United', 'Chatham Town'),
  (10, 'Whitehawk', 'Carshalton Athletic'),
  (10, 'Wingate & Finchley', 'Burgess Hill Town'),
  (10, 'Aveley', 'Brentwood Town'),
  (11, 'AFC Whyteleafe', 'Enfield Town'),
  (11, 'Leatherhead', 'Eastbourne Borough'),
  (11, 'Lewes', 'Dulwich Hamlet'),
  (11, 'Maldon & Tiptree', 'Dartford'),
  (11, 'Ramsgate', 'Cray Wanderers'),
  (11, 'St Albans City', 'Cheshunt'),
  (11, 'Stanway Rovers', 'Chatham Town'),
  (11, 'Three Bridges', 'Carshalton Athletic'),
  (11, 'Welling United', 'Burgess Hill Town'),
  (11, 'Whitehawk', 'Brentwood Town'),
  (11, 'Wingate & Finchley', 'Aveley'),
  (12, 'Eastbourne Borough', 'AFC Whyteleafe'),
  (12, 'Enfield Town', 'Dulwich Hamlet'),
  (12, 'Leatherhead', 'Dartford'),
  (12, 'Lewes', 'Cray Wanderers'),
  (12, 'Maldon & Tiptree', 'Cheshunt'),
  (12, 'Ramsgate', 'Chatham Town'),
  (12, 'St Albans City', 'Carshalton Athletic'),
  (12, 'Stanway Rovers', 'Burgess Hill Town'),
  (12, 'Three Bridges', 'Brentwood Town'),
  (12, 'Welling United', 'Aveley'),
  (12, 'Whitehawk', 'Wingate & Finchley'),
  (13, 'AFC Whyteleafe', 'Dulwich Hamlet'),
  (13, 'Eastbourne Borough', 'Dartford'),
  (13, 'Enfield Town', 'Cray Wanderers'),
  (13, 'Leatherhead', 'Cheshunt'),
  (13, 'Lewes', 'Chatham Town'),
  (13, 'Maldon & Tiptree', 'Carshalton Athletic'),
  (13, 'Ramsgate', 'Burgess Hill Town'),
  (13, 'St Albans City', 'Brentwood Town'),
  (13, 'Stanway Rovers', 'Aveley'),
  (13, 'Three Bridges', 'Wingate & Finchley'),
  (13, 'Welling United', 'Whitehawk'),
  (14, 'Dartford', 'AFC Whyteleafe'),
  (14, 'Dulwich Hamlet', 'Cray Wanderers'),
  (14, 'Eastbourne Borough', 'Cheshunt'),
  (14, 'Enfield Town', 'Chatham Town'),
  (14, 'Leatherhead', 'Carshalton Athletic'),
  (14, 'Lewes', 'Burgess Hill Town'),
  (14, 'Maldon & Tiptree', 'Brentwood Town'),
  (14, 'Ramsgate', 'Aveley'),
  (14, 'St Albans City', 'Wingate & Finchley'),
  (14, 'Stanway Rovers', 'Whitehawk'),
  (14, 'Three Bridges', 'Welling United'),
  (15, 'AFC Whyteleafe', 'Cray Wanderers'),
  (15, 'Dartford', 'Cheshunt'),
  (15, 'Dulwich Hamlet', 'Chatham Town'),
  (15, 'Eastbourne Borough', 'Carshalton Athletic'),
  (15, 'Enfield Town', 'Burgess Hill Town'),
  (15, 'Leatherhead', 'Brentwood Town'),
  (15, 'Lewes', 'Aveley'),
  (15, 'Maldon & Tiptree', 'Wingate & Finchley'),
  (15, 'Ramsgate', 'Whitehawk'),
  (15, 'St Albans City', 'Welling United'),
  (15, 'Stanway Rovers', 'Three Bridges'),
  (16, 'Cheshunt', 'AFC Whyteleafe'),
  (16, 'Cray Wanderers', 'Chatham Town'),
  (16, 'Dartford', 'Carshalton Athletic'),
  (16, 'Dulwich Hamlet', 'Burgess Hill Town'),
  (16, 'Eastbourne Borough', 'Brentwood Town'),
  (16, 'Enfield Town', 'Aveley'),
  (16, 'Leatherhead', 'Wingate & Finchley'),
  (16, 'Lewes', 'Whitehawk'),
  (16, 'Maldon & Tiptree', 'Welling United'),
  (16, 'Ramsgate', 'Three Bridges'),
  (16, 'St Albans City', 'Stanway Rovers'),
  (17, 'AFC Whyteleafe', 'Chatham Town'),
  (17, 'Cheshunt', 'Carshalton Athletic'),
  (17, 'Cray Wanderers', 'Burgess Hill Town'),
  (17, 'Dartford', 'Brentwood Town'),
  (17, 'Dulwich Hamlet', 'Aveley'),
  (17, 'Eastbourne Borough', 'Wingate & Finchley'),
  (17, 'Enfield Town', 'Whitehawk'),
  (17, 'Leatherhead', 'Welling United'),
  (17, 'Lewes', 'Three Bridges'),
  (17, 'Maldon & Tiptree', 'Stanway Rovers'),
  (17, 'Ramsgate', 'St Albans City'),
  (18, 'Carshalton Athletic', 'AFC Whyteleafe'),
  (18, 'Chatham Town', 'Burgess Hill Town'),
  (18, 'Cheshunt', 'Brentwood Town'),
  (18, 'Cray Wanderers', 'Aveley'),
  (18, 'Dartford', 'Wingate & Finchley'),
  (18, 'Dulwich Hamlet', 'Whitehawk'),
  (18, 'Eastbourne Borough', 'Welling United'),
  (18, 'Enfield Town', 'Three Bridges'),
  (18, 'Leatherhead', 'Stanway Rovers'),
  (18, 'Lewes', 'St Albans City'),
  (18, 'Maldon & Tiptree', 'Ramsgate'),
  (19, 'AFC Whyteleafe', 'Burgess Hill Town'),
  (19, 'Carshalton Athletic', 'Brentwood Town'),
  (19, 'Chatham Town', 'Aveley'),
  (19, 'Cheshunt', 'Wingate & Finchley'),
  (19, 'Cray Wanderers', 'Whitehawk'),
  (19, 'Dartford', 'Welling United'),
  (19, 'Dulwich Hamlet', 'Three Bridges'),
  (19, 'Eastbourne Borough', 'Stanway Rovers'),
  (19, 'Enfield Town', 'St Albans City'),
  (19, 'Leatherhead', 'Ramsgate'),
  (19, 'Lewes', 'Maldon & Tiptree'),
  (20, 'Brentwood Town', 'AFC Whyteleafe'),
  (20, 'Burgess Hill Town', 'Aveley'),
  (20, 'Carshalton Athletic', 'Wingate & Finchley'),
  (20, 'Chatham Town', 'Whitehawk'),
  (20, 'Cheshunt', 'Welling United'),
  (20, 'Cray Wanderers', 'Three Bridges'),
  (20, 'Dartford', 'Stanway Rovers'),
  (20, 'Dulwich Hamlet', 'St Albans City'),
  (20, 'Eastbourne Borough', 'Ramsgate'),
  (20, 'Enfield Town', 'Maldon & Tiptree'),
  (20, 'Leatherhead', 'Lewes'),
  (21, 'AFC Whyteleafe', 'Aveley'),
  (21, 'Brentwood Town', 'Wingate & Finchley'),
  (21, 'Burgess Hill Town', 'Whitehawk'),
  (21, 'Carshalton Athletic', 'Welling United'),
  (21, 'Chatham Town', 'Three Bridges'),
  (21, 'Cheshunt', 'Stanway Rovers'),
  (21, 'Cray Wanderers', 'St Albans City'),
  (21, 'Dartford', 'Ramsgate'),
  (21, 'Dulwich Hamlet', 'Maldon & Tiptree'),
  (21, 'Eastbourne Borough', 'Lewes'),
  (21, 'Enfield Town', 'Leatherhead'),
  (22, 'Wingate & Finchley', 'AFC Whyteleafe'),
  (22, 'Whitehawk', 'Aveley'),
  (22, 'Welling United', 'Brentwood Town'),
  (22, 'Three Bridges', 'Burgess Hill Town'),
  (22, 'Stanway Rovers', 'Carshalton Athletic'),
  (22, 'St Albans City', 'Chatham Town'),
  (22, 'Ramsgate', 'Cheshunt'),
  (22, 'Maldon & Tiptree', 'Cray Wanderers'),
  (22, 'Lewes', 'Dartford'),
  (22, 'Leatherhead', 'Dulwich Hamlet'),
  (22, 'Enfield Town', 'Eastbourne Borough'),
  (23, 'AFC Whyteleafe', 'Whitehawk'),
  (23, 'Welling United', 'Wingate & Finchley'),
  (23, 'Three Bridges', 'Aveley'),
  (23, 'Stanway Rovers', 'Brentwood Town'),
  (23, 'St Albans City', 'Burgess Hill Town'),
  (23, 'Ramsgate', 'Carshalton Athletic'),
  (23, 'Maldon & Tiptree', 'Chatham Town'),
  (23, 'Lewes', 'Cheshunt'),
  (23, 'Leatherhead', 'Cray Wanderers'),
  (23, 'Enfield Town', 'Dartford'),
  (23, 'Eastbourne Borough', 'Dulwich Hamlet'),
  (24, 'Welling United', 'AFC Whyteleafe'),
  (24, 'Three Bridges', 'Whitehawk'),
  (24, 'Stanway Rovers', 'Wingate & Finchley'),
  (24, 'St Albans City', 'Aveley'),
  (24, 'Ramsgate', 'Brentwood Town'),
  (24, 'Maldon & Tiptree', 'Burgess Hill Town'),
  (24, 'Lewes', 'Carshalton Athletic'),
  (24, 'Leatherhead', 'Chatham Town'),
  (24, 'Enfield Town', 'Cheshunt'),
  (24, 'Eastbourne Borough', 'Cray Wanderers'),
  (24, 'Dulwich Hamlet', 'Dartford'),
  (25, 'AFC Whyteleafe', 'Three Bridges'),
  (25, 'Stanway Rovers', 'Welling United'),
  (25, 'St Albans City', 'Whitehawk'),
  (25, 'Ramsgate', 'Wingate & Finchley'),
  (25, 'Maldon & Tiptree', 'Aveley'),
  (25, 'Lewes', 'Brentwood Town'),
  (25, 'Leatherhead', 'Burgess Hill Town'),
  (25, 'Enfield Town', 'Carshalton Athletic'),
  (25, 'Eastbourne Borough', 'Chatham Town'),
  (25, 'Dulwich Hamlet', 'Cheshunt'),
  (25, 'Dartford', 'Cray Wanderers'),
  (26, 'Stanway Rovers', 'AFC Whyteleafe'),
  (26, 'St Albans City', 'Three Bridges'),
  (26, 'Ramsgate', 'Welling United'),
  (26, 'Maldon & Tiptree', 'Whitehawk'),
  (26, 'Lewes', 'Wingate & Finchley'),
  (26, 'Leatherhead', 'Aveley'),
  (26, 'Enfield Town', 'Brentwood Town'),
  (26, 'Eastbourne Borough', 'Burgess Hill Town'),
  (26, 'Dulwich Hamlet', 'Carshalton Athletic'),
  (26, 'Dartford', 'Chatham Town'),
  (26, 'Cray Wanderers', 'Cheshunt'),
  (27, 'AFC Whyteleafe', 'St Albans City'),
  (27, 'Ramsgate', 'Stanway Rovers'),
  (27, 'Maldon & Tiptree', 'Three Bridges'),
  (27, 'Lewes', 'Welling United'),
  (27, 'Leatherhead', 'Whitehawk'),
  (27, 'Enfield Town', 'Wingate & Finchley'),
  (27, 'Eastbourne Borough', 'Aveley'),
  (27, 'Dulwich Hamlet', 'Brentwood Town'),
  (27, 'Dartford', 'Burgess Hill Town'),
  (27, 'Cray Wanderers', 'Carshalton Athletic'),
  (27, 'Cheshunt', 'Chatham Town'),
  (28, 'Ramsgate', 'AFC Whyteleafe'),
  (28, 'Maldon & Tiptree', 'St Albans City'),
  (28, 'Lewes', 'Stanway Rovers'),
  (28, 'Leatherhead', 'Three Bridges'),
  (28, 'Enfield Town', 'Welling United'),
  (28, 'Eastbourne Borough', 'Whitehawk'),
  (28, 'Dulwich Hamlet', 'Wingate & Finchley'),
  (28, 'Dartford', 'Aveley'),
  (28, 'Cray Wanderers', 'Brentwood Town'),
  (28, 'Cheshunt', 'Burgess Hill Town'),
  (28, 'Chatham Town', 'Carshalton Athletic'),
  (29, 'AFC Whyteleafe', 'Maldon & Tiptree'),
  (29, 'Lewes', 'Ramsgate'),
  (29, 'Leatherhead', 'St Albans City'),
  (29, 'Enfield Town', 'Stanway Rovers'),
  (29, 'Eastbourne Borough', 'Three Bridges'),
  (29, 'Dulwich Hamlet', 'Welling United'),
  (29, 'Dartford', 'Whitehawk'),
  (29, 'Cray Wanderers', 'Wingate & Finchley'),
  (29, 'Cheshunt', 'Aveley'),
  (29, 'Chatham Town', 'Brentwood Town'),
  (29, 'Carshalton Athletic', 'Burgess Hill Town'),
  (30, 'Lewes', 'AFC Whyteleafe'),
  (30, 'Leatherhead', 'Maldon & Tiptree'),
  (30, 'Enfield Town', 'Ramsgate'),
  (30, 'Eastbourne Borough', 'St Albans City'),
  (30, 'Dulwich Hamlet', 'Stanway Rovers'),
  (30, 'Dartford', 'Three Bridges'),
  (30, 'Cray Wanderers', 'Welling United'),
  (30, 'Cheshunt', 'Whitehawk'),
  (30, 'Chatham Town', 'Wingate & Finchley'),
  (30, 'Carshalton Athletic', 'Aveley'),
  (30, 'Burgess Hill Town', 'Brentwood Town'),
  (31, 'AFC Whyteleafe', 'Leatherhead'),
  (31, 'Enfield Town', 'Lewes'),
  (31, 'Eastbourne Borough', 'Maldon & Tiptree'),
  (31, 'Dulwich Hamlet', 'Ramsgate'),
  (31, 'Dartford', 'St Albans City'),
  (31, 'Cray Wanderers', 'Stanway Rovers'),
  (31, 'Cheshunt', 'Three Bridges'),
  (31, 'Chatham Town', 'Welling United'),
  (31, 'Carshalton Athletic', 'Whitehawk'),
  (31, 'Burgess Hill Town', 'Wingate & Finchley'),
  (31, 'Brentwood Town', 'Aveley'),
  (32, 'Enfield Town', 'AFC Whyteleafe'),
  (32, 'Eastbourne Borough', 'Leatherhead'),
  (32, 'Dulwich Hamlet', 'Lewes'),
  (32, 'Dartford', 'Maldon & Tiptree'),
  (32, 'Cray Wanderers', 'Ramsgate'),
  (32, 'Cheshunt', 'St Albans City'),
  (32, 'Chatham Town', 'Stanway Rovers'),
  (32, 'Carshalton Athletic', 'Three Bridges'),
  (32, 'Burgess Hill Town', 'Welling United'),
  (32, 'Brentwood Town', 'Whitehawk'),
  (32, 'Aveley', 'Wingate & Finchley'),
  (33, 'AFC Whyteleafe', 'Eastbourne Borough'),
  (33, 'Dulwich Hamlet', 'Enfield Town'),
  (33, 'Dartford', 'Leatherhead'),
  (33, 'Cray Wanderers', 'Lewes'),
  (33, 'Cheshunt', 'Maldon & Tiptree'),
  (33, 'Chatham Town', 'Ramsgate'),
  (33, 'Carshalton Athletic', 'St Albans City'),
  (33, 'Burgess Hill Town', 'Stanway Rovers'),
  (33, 'Brentwood Town', 'Three Bridges'),
  (33, 'Aveley', 'Welling United'),
  (33, 'Wingate & Finchley', 'Whitehawk'),
  (34, 'Dulwich Hamlet', 'AFC Whyteleafe'),
  (34, 'Dartford', 'Eastbourne Borough'),
  (34, 'Cray Wanderers', 'Enfield Town'),
  (34, 'Cheshunt', 'Leatherhead'),
  (34, 'Chatham Town', 'Lewes'),
  (34, 'Carshalton Athletic', 'Maldon & Tiptree'),
  (34, 'Burgess Hill Town', 'Ramsgate'),
  (34, 'Brentwood Town', 'St Albans City'),
  (34, 'Aveley', 'Stanway Rovers'),
  (34, 'Wingate & Finchley', 'Three Bridges'),
  (34, 'Whitehawk', 'Welling United'),
  (35, 'AFC Whyteleafe', 'Dartford'),
  (35, 'Cray Wanderers', 'Dulwich Hamlet'),
  (35, 'Cheshunt', 'Eastbourne Borough'),
  (35, 'Chatham Town', 'Enfield Town'),
  (35, 'Carshalton Athletic', 'Leatherhead'),
  (35, 'Burgess Hill Town', 'Lewes'),
  (35, 'Brentwood Town', 'Maldon & Tiptree'),
  (35, 'Aveley', 'Ramsgate'),
  (35, 'Wingate & Finchley', 'St Albans City'),
  (35, 'Whitehawk', 'Stanway Rovers'),
  (35, 'Welling United', 'Three Bridges'),
  (36, 'Cray Wanderers', 'AFC Whyteleafe'),
  (36, 'Cheshunt', 'Dartford'),
  (36, 'Chatham Town', 'Dulwich Hamlet'),
  (36, 'Carshalton Athletic', 'Eastbourne Borough'),
  (36, 'Burgess Hill Town', 'Enfield Town'),
  (36, 'Brentwood Town', 'Leatherhead'),
  (36, 'Aveley', 'Lewes'),
  (36, 'Wingate & Finchley', 'Maldon & Tiptree'),
  (36, 'Whitehawk', 'Ramsgate'),
  (36, 'Welling United', 'St Albans City'),
  (36, 'Three Bridges', 'Stanway Rovers'),
  (37, 'AFC Whyteleafe', 'Cheshunt'),
  (37, 'Chatham Town', 'Cray Wanderers'),
  (37, 'Carshalton Athletic', 'Dartford'),
  (37, 'Burgess Hill Town', 'Dulwich Hamlet'),
  (37, 'Brentwood Town', 'Eastbourne Borough'),
  (37, 'Aveley', 'Enfield Town'),
  (37, 'Wingate & Finchley', 'Leatherhead'),
  (37, 'Whitehawk', 'Lewes'),
  (37, 'Welling United', 'Maldon & Tiptree'),
  (37, 'Three Bridges', 'Ramsgate'),
  (37, 'Stanway Rovers', 'St Albans City'),
  (38, 'Chatham Town', 'AFC Whyteleafe'),
  (38, 'Carshalton Athletic', 'Cheshunt'),
  (38, 'Burgess Hill Town', 'Cray Wanderers'),
  (38, 'Brentwood Town', 'Dartford'),
  (38, 'Aveley', 'Dulwich Hamlet'),
  (38, 'Wingate & Finchley', 'Eastbourne Borough'),
  (38, 'Whitehawk', 'Enfield Town'),
  (38, 'Welling United', 'Leatherhead'),
  (38, 'Three Bridges', 'Lewes'),
  (38, 'Stanway Rovers', 'Maldon & Tiptree'),
  (38, 'St Albans City', 'Ramsgate'),
  (39, 'AFC Whyteleafe', 'Carshalton Athletic'),
  (39, 'Burgess Hill Town', 'Chatham Town'),
  (39, 'Brentwood Town', 'Cheshunt'),
  (39, 'Aveley', 'Cray Wanderers'),
  (39, 'Wingate & Finchley', 'Dartford'),
  (39, 'Whitehawk', 'Dulwich Hamlet'),
  (39, 'Welling United', 'Eastbourne Borough'),
  (39, 'Three Bridges', 'Enfield Town'),
  (39, 'Stanway Rovers', 'Leatherhead'),
  (39, 'St Albans City', 'Lewes'),
  (39, 'Ramsgate', 'Maldon & Tiptree'),
  (40, 'Burgess Hill Town', 'AFC Whyteleafe'),
  (40, 'Brentwood Town', 'Carshalton Athletic'),
  (40, 'Aveley', 'Chatham Town'),
  (40, 'Wingate & Finchley', 'Cheshunt'),
  (40, 'Whitehawk', 'Cray Wanderers'),
  (40, 'Welling United', 'Dartford'),
  (40, 'Three Bridges', 'Dulwich Hamlet'),
  (40, 'Stanway Rovers', 'Eastbourne Borough'),
  (40, 'St Albans City', 'Enfield Town'),
  (40, 'Ramsgate', 'Leatherhead'),
  (40, 'Maldon & Tiptree', 'Lewes'),
  (41, 'AFC Whyteleafe', 'Brentwood Town'),
  (41, 'Aveley', 'Burgess Hill Town'),
  (41, 'Wingate & Finchley', 'Carshalton Athletic'),
  (41, 'Whitehawk', 'Chatham Town'),
  (41, 'Welling United', 'Cheshunt'),
  (41, 'Three Bridges', 'Cray Wanderers'),
  (41, 'Stanway Rovers', 'Dartford'),
  (41, 'St Albans City', 'Dulwich Hamlet'),
  (41, 'Ramsgate', 'Eastbourne Borough'),
  (41, 'Maldon & Tiptree', 'Enfield Town'),
  (41, 'Lewes', 'Leatherhead'),
  (42, 'Aveley', 'AFC Whyteleafe'),
  (42, 'Wingate & Finchley', 'Brentwood Town'),
  (42, 'Whitehawk', 'Burgess Hill Town'),
  (42, 'Welling United', 'Carshalton Athletic'),
  (42, 'Three Bridges', 'Chatham Town'),
  (42, 'Stanway Rovers', 'Cheshunt'),
  (42, 'St Albans City', 'Cray Wanderers'),
  (42, 'Ramsgate', 'Dartford'),
  (42, 'Maldon & Tiptree', 'Dulwich Hamlet'),
  (42, 'Lewes', 'Eastbourne Borough'),
  (42, 'Leatherhead', 'Enfield Town')
) as f(gw_number, home_name, away_name)
join public.gameweeks gw on gw.number = f.gw_number and gw.league_slug = 'isthmian-premier' and gw.season = '2026-27'
join public.teams home on home.name = f.home_name and home.league_slug = 'isthmian-premier'
join public.teams away on away.name = f.away_name and away.league_slug = 'isthmian-premier'
where not exists (
  select 1 from public.fixtures existing
  where existing.gameweek_id = gw.id and existing.home_team_id = home.id and existing.away_team_id = away.id
);

